"""Split authored sign/facade atlases at inspected gutters; no semantic repainting."""
from pathlib import Path
from PIL import Image
import shutil,json
ROOT=Path(__file__).resolve().parents[1]
DOC=ROOT/'Documentation/Urban'; SRC=DOC/'Sources'; OUT=ROOT/'Assets/AfterSignal/Resources/Art/Urban'
SRC.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True)
names=['exec-a4b94d7f-d89c-4bdc-8e30-8995f4b420de.png','exec-2da19048-5cd5-462c-843b-61455f2c2b3e.png']
for name in names:
    if not (SRC/name).exists():shutil.copy2(Path('C:/Users/82105/.codex/generated_images/01a0732c-239b-7072-99fe-6782f54c0ec8')/name,SRC/name)
sign=Image.open(SRC/names[0]).convert('RGB'); fac=Image.open(SRC/names[1]).convert('RGB')
assert sign.size==(1536,1024) and fac.size==(1024,1536),(sign.size,fac.size)
rows=[(12,143),(152,282),(289,416),(426,550),(559,675),(684,791),(800,901),(910,1014)]
for r,(a,b) in enumerate(rows):
    for c,(x,z) in enumerate([(19,759),(778,1517)]):sign.crop((x,a,z,b)).resize((1024,180),Image.Resampling.LANCZOS).save(OUT/f'Sign-{r*2+c:02}.png')
for r,(a,b) in enumerate([(8,462),(471,835),(845,1180),(1190,1529)]):
    for c,(x,z) in enumerate([(9,507),(518,1015)]):fac.crop((x,a,z,b)).save(OUT/f'Facade-{r*2+c:02}.png')
surface_name='exec-89ace853-1146-44d3-a6b8-b33241be3c46.png'
surface=Image.open(SRC/surface_name).convert('RGB')
assert surface.size==(1536,1024)
for i in range(6):
    x=(i%3)*512;y=(i//3)*512
    surface.crop((x,y,x+512,y+512)).save(OUT/f'Surface-{i:02}.png')
(DOC/'sources.json').write_text(json.dumps({'sources':names+[surface_name],'origin':'Original AI-generated art created for AFTERSIGNAL.','processing':'Inspected gutter crop and resize only. Korean lettering reviewed in source and game. Road markings are exact original raster graphics generated by CityStreetBuilder, not borrowed images.'},ensure_ascii=False,indent=2),encoding='utf-8')
print('16 Korean signs, 8 facade panels and 6 surface tiles prepared.')
