from pathlib import Path
R=Path(__file__).resolve().parents[1]/'Assets/AfterSignal'
def change(file,a,b):
 p=R/file;s=p.read_text(encoding='utf-8-sig');assert a in s,(file,a[:70]);p.write_text(s.replace(a,b),encoding='utf-8')
change('Runtime/GameTuning.cs','Headquarters, Breach }','Headquarters, Breach, UrbanCity, UrbanInterior }')
change('Runtime/GameTuning.cs','"23_FacadeBreach" };','"23_FacadeBreach", "24_OpenCity", "25_CityInterior" };')
change('Runtime/CivicWorld.cs','stage==StageId.Headquarters;','stage==StageId.Headquarters||stage==StageId.UrbanInterior;')
change('Runtime/CivicWorld.cs','stage==StageId.Haven||Interior(stage)','stage==StageId.Haven||stage==StageId.UrbanCity||Interior(stage)')
change('Runtime/CivicWorld.cs','"애프터라이트 학교"','"새봄초등학교"')
change('Runtime/CivicWorld.cs','"온유 병원"','"온유병원"')
change('Runtime/CivicWorld.cs','"신호 구조대 본부":"애프터라이트"','"신호복원본부":stage==StageId.UrbanInterior?UrbanCatalog.Name(UrbanCatalog.Current):"애프터라이트"')
change('Runtime/PlayerInputReader.cs','pause, reload;','pause, reload, map, exit;')
change('Runtime/PlayerInputReader.cs','weaponCycle=Mouse.current','map=Keyboard.current!=null&&Keyboard.current.mKey.wasPressedThisFrame, exit=Keyboard.current!=null&&Keyboard.current.fKey.wasPressedThisFrame, weaponCycle=Mouse.current')
change('Runtime/GameDirector.cs','float remaining=dt;','UrbanSimulation.Instance?.BeforeInput(ref control,dt);\n            float remaining=dt;')
change('Runtime/GameDirector.cs','Player.Tick(control,step);','if(UrbanSimulation.Instance&&UrbanSimulation.Instance.Driving)UrbanSimulation.Instance.Tick(control,step);else Player.Tick(control,step);')
change('Runtime/GameDirector.cs','if(control.interact&&Nearby)','if(control.interact&&Nearby&&!(UrbanSimulation.Instance&&UrbanSimulation.Instance.Driving))')
change('Runtime/GameDirector.cs','if(stage==StageId.Residence)return','if(stage==StageId.UrbanCity)return "M 도시 지도 · E 차량 탑승 / 건물 출입 · 주유소에서 연료 보충";\n                if(stage==StageId.UrbanInterior)return UrbanCatalog.Name(UrbanCatalog.Current)+" · 직원과 대화 / 출입문으로 돌아가기";\n                if(stage==StageId.Residence)return')
change('Runtime/GameDirector.cs','ResetExpansion();CivicWorld.ClearArrival();','ResetExpansion();CivicWorld.ClearArrival();UrbanCatalog.Reset();')
change('Runtime/GameDirector.cs','Transition=true;Player.Rope.Release();','Transition=true;Player.Rope.Release();UrbanSimulation.Instance?.SaveCar();')
change('Runtime/GameDirector.cs','if(System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"-residence-smoke")>=0)','if(System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"-urban-smoke")>=0)gameObject.AddComponent<UrbanSmoke>();\n            if(System.Array.IndexOf(System.Environment.GetCommandLineArgs(),"-residence-smoke")>=0)')
change('Runtime/InteractionPoint.cs','FirstRail, BreachMission }','FirstRail, BreachMission, UrbanEnter, UrbanExit, UrbanTown, UrbanService }')
change('Runtime/InteractionPoint.cs','public StageId destination;','public int siteId;public StageId destination;')
change('Runtime/InteractionPoint.cs','switch(kind){','switch(kind){\n                case InteractionKind.UrbanEnter:UrbanCatalog.Enter(game,siteId);break;\n                case InteractionKind.UrbanExit:UrbanCatalog.Exit(game);break;\n                case InteractionKind.UrbanTown:CivicWorld.Travel(game,StageId.Haven,new Vector3(215,.15f,-8));break;\n                case InteractionKind.UrbanService:if(UrbanCatalog.Kind(UrbanCatalog.Current)==4||UrbanCatalog.Kind(UrbanCatalog.Current)==9||UrbanCatalog.Kind(UrbanCatalog.Current)==15)game.Player.Heal(100);game.ShowDialogue(UrbanCatalog.Name(UrbanCatalog.Current),UrbanCatalog.Descriptions[UrbanCatalog.Kind(UrbanCatalog.Current)]);break;')
change('Runtime/CameraRig.cs','Quaternion Angle=>','Quaternion Angle=>director.stage==StageId.UrbanCity?Quaternion.Euler(44,-8,0):UrbanSimulation.Instance&&UrbanSimulation.Instance.Driving?Quaternion.Euler(30,-8,0):')
change('Runtime/CameraRig.cs','var p=director.Player;float distance','var p=director.Player;\n            if(director.stage==StageId.UrbanCity){bool driving=UrbanSimulation.Instance&&UrbanSimulation.Instance.Driving;var forward=driving?UrbanSimulation.Instance.Current.Forward*UrbanSimulation.Instance.Current.speed*.18f:Vector3.zero;return p.transform.position+forward+new Vector3(5,driving?29:22,driving?-29:-22);}\n            if(UrbanSimulation.Instance&&UrbanSimulation.Instance.Driving)return p.transform.position+new Vector3(4,16,-26);\n            float distance')
change('Editor/WorldBuilder.cs','if(stage==StageId.Residence)Residence();else','if(stage==StageId.UrbanCity){game.stageLength=790;game.halfDepth=330;game.spawn=new Vector3(50,.15f,-295);BuildUrbanCity();}else if(stage==StageId.UrbanInterior){game.stageLength=58;game.halfDepth=19;game.spawn=new Vector3(5,.15f,-10);BuildUrbanInterior();}else if(stage==StageId.Residence)Residence();else')
change('Editor/WorldBuilder.cs','Box("Sign / "+title','int image=UrbanSignIndex(title);if(image>=0&&AssetDatabase.LoadAssetAtPath<Texture2D>(resourceRoot+"Art/Urban/Sign-"+image.ToString("00")+".png")){UrbanPlate(image,pos,width,Mathf.Max(height,width/5.7f),parent);return;}\n            Box("Sign / "+title')
change('Editor/PerformanceBake.cs','if(filter.GetComponentInParent<FoliageOcclusion>()','if(filter.GetComponentInParent<CityVehicle>()||filter.GetComponentInParent<CityBuildingCutaway>()||filter.GetComponentInParent<FoliageOcclusion>()')
change('Editor/ResidenceBuilder.cs','static void InstallBackdrop(StageId stage,float length)\n        {','static void InstallBackdrop(StageId stage,float length)\n        {\n            if(stage==StageId.UrbanCity||stage==StageId.UrbanInterior)return;')
change('Runtime/CivicHud.cs','if(game.stage!=StageId.Haven){','if(game.stage==StageId.UrbanCity){BuildUrbanMap(civicMap.transform);return;}\n            if(game.stage!=StageId.Haven){')
change('Runtime/SignalHud.cs','fade.gameObject.SetActive(game.Transition);','UpdateUrbanHud();\n            fade.gameObject.SetActive(game.Transition);')
print('Integrated appended stages, vehicle control routing, urban interactions, camera and HUD.')
